name1=input("Give a name: ")
number1=input("Give a number: ")
noun1=input("Give a noun: ")
place1=input("Give a place: ")
pluralnoun1=input("Give a noun: ")
adjective1=input("Give an adjective: ")
verb1=input("Give a verb: ")
job1=input("Give a job: ")
place2=input("Give a place: ")
time1=input("Give a time: ")
verb2=input("Give a verb: ")
verb3=input("Give a verb: ")
time2=input("Give a time: ")
number2=input("Give a number: ")
noun2=input("Give a noun: ")
liquid1=input("Give a liquid: ")
number3=input("Give a number: ")
verb4=input("Give a verb: ")
pluralNoun2=input("Give a plural noun: ")
adjective2=input("Give an adjective: ")
pluralNoun3=input("Give a plural noun: ")
ingVerb1=input("Give a verb ending with -ing: ")
ingVerb2=input("Give a verb ending with -ing: ")
noun3=input("Give a noun: ")
noun4=input("Give a noun: ")
verb5=input("Give a verb: ")

print("My name is "+name1+".")
print("I am "+number1+" years old.")
print("My "+noun1+" is in the northeast section of "+place1+", where all the "+pluralnoun1+" are, and I am not "+adjective1+".")
print("I "+verb1+" as an "+job1+" for the "+place2+", and I get home everyday by "+time1+" at the latest.")
print("I don't "+verb2+", but I occasionally "+verb3+".")
print("I'm in bed by "+time2+", and make sure I get "+number2+" hours of sleep, no matter what.")
print("After having a "+noun2+" of "+liquid1+" and doing about "+number3+" minutes of stretches before "+verb4+" going to bed, I usually have no "+pluralNoun2+" sleeping until morning.")
print("Just like a baby, I wake up without any fatigue or stress in the morning.")
print("I was told there were no issues at my last check-up.")
print("I'm trying to explain that I'm a person who wishes to live a very "+adjective2+" life.")
print("I take care not to trouble myself with any "+pluralNoun3+", like "+ingVerb1+" and "+ingVerb2+", that would cause me to lose "+noun3+" at night.")
print("That is how I deal with society, and I know that is what brings me "+noun4+".")
print("Although, if I were to "+verb5+" I wouldn't lose to anyone.")