name1=input("Give a name: ")
number1=input("Give a number: ")
noun1=input("Give a noun: ")
place1=input("Give a place: ")
pluralnoun1=input("Give a noun: ")
adjective1=input("Give an adjective: ")
verb1=input("Give a verb: ")
job1=input("Give a job: ")
place2=input("Give a place: ")
time1=input("Give a time: ")
verb2=input("Give a verb: ")
verb3=input("Give a verb: ")
time2=input("Give a time: ")
number2=input("Give a number: ")
noun3=input("Give a noun: ")
liquid1=input("Give a liquid: ")
number3=input("Give a number: ")
verb4=input("Give a verb: ")
pluralNoun2=input("Give a plural noun: ")
adjective2=input("Give an adjective: ")
pluralNoun3=input("Give a plural noun: ")
ingVerb1=input("Give a verb ending with -ing: ")
ingVerb2=input("Give a verb ending with -ing: ")
noun4=input("Give a noun: ")
noun5=input("Give a noun: ")
verb5=input("Give a verb: ")

print("My name is "+name1+".")
print("I am "+number1+" years old.")
print("My "+noun1+" is in the northeast section of "+place1+", where all the "+pluralnoun1+" are, and I am not "+adjective1+".")